version: '3'

services:
  labcr:
    networks: [proxy]
    environment:
      VIRTUAL_HOST: cr.fracz.pl
      LETSENCRYPT_HOST: cr.fracz.pl
      LETSENCRYPT_EMAIL: fraczwojciech@gmail.com
    expose: [80]

networks:
  proxy:
    external:
      name: webproxy
